sudo: false
language: python
env:
    - DJANGO_VERSION=2.1
    - DJANGO_VERSION=1.11
    - DJANGO_VERSION=1.10
    - DJANGO_VERSION=1.8
python:
  - 2.7
  - 3.6
# https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python 3.7
      dist: xenial
      sudo: true
install: pip install -r dev-requirements.txt
script:
  - tox
  - flake8 sendgrid_backend/
