name: Python package

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
    - name: flake8
      run: flake8 sendgrid_backend/
    - name: isort
      run: isort -c ./
    - name: black
      run: black --check ./
    - name: mypy
      run: mypy sendgrid_backend/

  test:
    environment: 'Live API Test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - run: echo ${{ secrets.THISSECRETDOESNOTEXIST }}
